#cloud-config
groups:
  - mpusers

users:
  - default
  - name: ubuntu
    groups: mpusers
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - SSH_PUBLIC_KEY_STRING

package_update: true

packages:
 - apt-transport-https
 - gnupg
 - ca-certificates
 - wget
 - curl
 - apt-utils
 - net-tools

write_files:
  - path: /opt/scripts/install_docker.sh
    content: |-
      #!/bin/bash
      apt-get update 
      curl https://get.docker.com | sudo bash
      usermod -aG docker ubuntu 
      curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose \
      chmod +x /usr/local/bin/docker-compose
    owner: root:root
    path: /opt/scripts/install_docker.sh
    permissions: '0755'

bootcmd:
  - mkdir -p /opt/scripts

runcmd:
 - /opt/scripts/install_docker.sh

