#cloud-config
groups:
  - mpusers

users:
  - default
  - name: ubuntu
    groups: mpusers
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - REPLACEME_SSH_PUBLIC_KEY

package_update: true

packages:
  - apt-transport-https
  - gnupg
  - ca-certificates
  - wget
  - curl
  - apt-utils
  - net-tools

bootcmd:
  - mkdir -p /opt/scripts

write_files:
  - content: |-
      #!/usr/bin/env bash
      set -x
      apt update
      export K3S_VERSION=v1.24.3+k3s1
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_VERSION=${K3S_VERSION} INSTALL_K3S_EXEC="--disable=traefik" sh -s -
      # https://github.com/k3s-io/k3s/issues/1160#issuecomment-1058846505
      mkdir -p /home/ubuntu/.kube
      cp /etc/rancher/k3s/k3s.yaml /home/ubuntu/.kube/config
      chown ubuntu:ubuntu /home/ubuntu/.kube/config
      chmod 0400 /home/ubuntu/.kube/config
    owner: root:root
    path: /opt/scripts/install_k3s.sh
    permissions: '0755'
  - content: |-
      #!/usr/bin/env bash
      set -x
      curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    owner: root:root
    path: /opt/scripts/install_helm.sh
    permissions: '0755'
  - content: |
      KUBECONFIG="/home/ubuntu/.kube/config"
      K3S_VERSION="v1.24.3+k3s1"
    path: /etc/environment
    append: true
runcmd:
  - /opt/scripts/install_k3s.sh >> /var/log/install-k3s.log
  - /opt/scripts/install_helm.sh >> /var/log/install-helm.log
