#cloud-config
groups:
  - mpusers

users:
  - default
  - name: ubuntu
    groups: mpusers
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - SSH_PUBLIC_KEY_STRING

package_update: true

packages:
 - apt-transport-https
 - gnupg
 - ca-certificates
 - wget
 - apt-utils
 - postgresql 
 - postgresql-contrib

write_files:
  - path: /etc/profile.d/custom.sh
    content: |
      #!/bin/bash
      export PATH="${PATH}:/usr/local/concourse/bin"
    append: true
    owner: root:root
    permissions: '0755'

  - path: /etc/concourse/web_environment
    content: |
      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/concourse/bin
      CONCOURSE_ADD_LOCAL_USER=admin:pass
      CONCOURSE_SESSION_SIGNING_KEY=/etc/concourse/session_signing_key
      CONCOURSE_TSA_HOST_KEY=/etc/concourse/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS=/etc/concourse/authorized_worker_keys
      CONCOURSE_POSTGRES_HOST=127.0.0.1
      CONCOURSE_POSTGRES_USER=concourse
      CONCOURSE_POSTGRES_PASSWORD=concourse
      CONCOURSE_POSTGRES_DATABASE=atc
      CONCOURSE_MAIN_TEAM_LOCAL_USER=admin
      CONCOURSE_EXTERNAL_URL=http://IP_ADDRESS:8080
    owner: root:root
    permissions: '600'

  - path: /etc/concourse/worker_environment
    content: |
      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/concourse/bin
      CONCOURSE_WORK_DIR=/var/lib/concourse
      CONCOURSE_TSA_HOST=127.0.0.1:2222
      CONCOURSE_TSA_PUBLIC_KEY=/etc/concourse/tsa_host_key.pub
      CONCOURSE_TSA_WORKER_PRIVATE_KEY=/etc/concourse/worker_key
      CONCOURSE_GARDEN_DNS_SERVER=8.8.8.8
    owner: root:root
    permissions: '600'

  - path: /etc/systemd/system/concourse-web.service
    content: |
      [Unit]
      Description=Concourse CI web process (ATC and TSA)
      After=postgresql.service
      [Service]
      User=concourse
      Restart=on-failure
      EnvironmentFile=/etc/concourse/web_environment
      ExecStart=/usr/local/concourse/bin/concourse web
      [Install]
      WantedBy=multi-user.target
    owner: root:root

  - path: /etc/systemd/system/concourse-worker.service
    content: |
      [Unit]
      Description=Concourse CI worker process
      After=concourse-web.service
      [Service]
      User=root
      Restart=on-failure
      EnvironmentFile=/etc/concourse/worker_environment
      ExecStart=/usr/local/concourse/bin/concourse worker
      [Install]
      WantedBy=multi-user.target
    owner: root:root

  - path: /opt/scripts/install_concourse.sh
    content: |-
      #!/bin/bash
      sudo -u postgres createuser concourse
      sudo -u postgres createdb --owner=concourse atc
      wget https://github.com/concourse/concourse/releases/download/v6.7.6/concourse-6.7.6-linux-amd64.tgz
      wget https://github.com/concourse/concourse/releases/download/v6.7.6/fly-6.7.6-linux-amd64.tgz
      tar -xvf concourse-6.7.6-linux-amd64.tgz -C /usr/local/
      mkdir -p /etc/concourse
      mkdir -p /var/lib/concourse
      ssh-keygen -t rsa -q -N '' -f /etc/concourse/worker_key -m pem
      ssh-keygen -t rsa -q -N '' -f /etc/concourse/session_signing_key -m pem
      ssh-keygen -t rsa -q -N '' -f /etc/concourse/tsa_host_key -m pem
      cp /etc/concourse/worker_key.pub /etc/concourse/authorized_worker_keys
      adduser --system --group concourse
      chown -R concourse:concourse /etc/concourse /var/lib/concourse
      tar -xf fly-6.7.6-linux-amd64.tgz
      mv fly /usr/bin/fly
      rm -rf fly-6.7.6-linux-amd64.tgz
      rm -rf concourse-6.7.6-linux-amd64.tgz
    owner: root:root
    permissions: '0755'

bootcmd:
  - mkdir -p /opt/scripts
  #- echo "net.ipv6.conf.all.disable_ipv6=1" >> /etc/sysctl.conf
  #- echo "net.ipv6.conf.default.disable_ipv6=1" >> /etc/sysctl.conf
  #- sysctl -p

runcmd:
 - echo "source /etc/profile.d/custom.sh" >> /home/ubuntu/.bashrc
 - chown ubuntu:ubuntu /home/ubuntu/.bashrc
 - /opt/scripts/install_concourse.sh
 - export NETWORK_INTERFACE=enp0s2
 - export IP=$(ip addr show dev ${NETWORK_INTERFACE} | grep -w 'inet' | awk '{print $2}' | cut -d '/' -f1)
 - sed -i "s/IP_ADDRESS/${IP}/g" /etc/concourse/web_environment
 - sudo -S -u postgres -i /bin/bash -l -c 'psql -U postgres -d atc -c "ALTER USER concourse WITH PASSWORD '"'concourse';"'"'
 - chown -R concourse:concourse /etc/concourse /var/lib/concourse
 - chmod 600 /etc/concourse/*_environment
 - systemctl daemon-reload
 - systemctl restart concourse-web concourse-worker
 - systemctl enable concourse-web concourse-worker postgresql

#power_state:
#  mode: reboot
#  message: Restarting after installing concourse
